declare module "*cors";
declare module "*express";
declare module "*bcrypt";
declare module "*jsonwebtoken";
declare module "*path";
declare module "*multer";
declare module "*google";
// delcare module
// delcare module
// delcare module
// delcare module
